### ISSUE TITLE
CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered

### ISSUE THREAD

**Issue by mrdncr** [mrdncr/community-detection-cuda#9]
Sometimes the following exception is thrown

0) V: 334863, E: 1851744, Q: -6.22817e-06, Clone: 0.011257, Move: 1.60025, Refine: 1.5948, Aggregate: 1.41125, Total: 4.61755
1) V: 85659, E: 624019, Q: 0.430619, Clone: 0.00267, Move: 0.51578, Refine: 0.344278, Aggregate: 0.235773, Total: 1.0985
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorIllegalAddress: an illegal memory access was encountered

**Comment by isil-oz** [comment]
The following is another exception that occurred frequently, but not always (in NVIDIA GeForce RTX 3050 Ti Laptop GPU):
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  uninitialized_fill_n: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
